spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/loantrendhub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: Yn@856391
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mysql.sql

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB

server:
  port: 18090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 60000
    uri-encoding: UTF-8
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    org.springframework.jdbc.core: INFO
    om.zaxxer.hikari: INFO
app:
  query:
    fill-missing-with-zero: true